from datetime import datetime

from bson import ObjectId

from langchain_core.messages import (
    HumanMessage,
    AIMessage,
    ToolMessage,
)

from app.database.session import database
from app.graph.agent import agent


class ChatService:

    @staticmethod
    async def get_messages(
        conversation_id: str,
    ):
        messages = await (
            database.messages.find(
                {
                    "conversation_id": conversation_id
                }
            )
            .sort("created_at", 1)
            .to_list(None)
        )

        return messages

    @staticmethod
    def convert_messages(
        db_messages,
    ):
        messages = []

        for msg in db_messages:

            if msg["role"] == "user":

                messages.append(
                    HumanMessage(
                        content=msg["content"]
                    )
                )

            elif msg["role"] == "assistant":

                messages.append(
                    AIMessage(
                        content=msg["content"],
                        tool_calls=msg.get("tool_calls") or []
                    )
                )

            elif msg["role"] == "tool":

                messages.append(
                    ToolMessage(
                        content=msg["content"],
                        tool_call_id=msg["tool_call_id"],
                        name=msg.get("name")
                    )
                )

        return messages

    @staticmethod
    async def save_message(
        conversation_id: str,
        role: str,
        content: str,
        tool_calls: list = None,
        tool_call_id: str = None,
        name: str = None,
    ):
        doc = {
            "conversation_id": conversation_id,
            "role": role,
            "content": content,
            "created_at": datetime.utcnow(),
        }
        if tool_calls is not None:
            doc["tool_calls"] = tool_calls
        if tool_call_id is not None:
            doc["tool_call_id"] = tool_call_id
        if name is not None:
            doc["name"] = name

        await database.messages.insert_one(doc)

    @classmethod
    async def chat(
        cls,
        conversation_id: str,
        user_message: str,
    ):
        # 1. Save user message immediately
        await cls.save_message(
            conversation_id=conversation_id,
            role="user",
            content=user_message,
        )

        # 2. Update conversation timestamp immediately
        await database.conversations.update_one(
            {
                "_id": ObjectId(conversation_id)
            },
            {
                "$set": {
                    "updated_at": datetime.utcnow()
                }
            }
        )

        # 3. Load previous conversation history (which now includes the user message)
        db_messages = await cls.get_messages(
            conversation_id
        )

        # 4. Convert MongoDB messages -> LangChain messages
        messages = cls.convert_messages(
            db_messages
        )

        # 5. Invoke LangGraph Agent
        response = await agent.ainvoke(
            {
                "messages": messages
            }
        )

        print("\n===== RAW AGENT RESPONSE =====\n")
        print(response)

        # 6. Save each new message generated by the agent
        new_messages = response["messages"][len(messages):]
        for msg in new_messages:
            if isinstance(msg, AIMessage):
                await cls.save_message(
                    conversation_id=conversation_id,
                    role="assistant",
                    content=msg.content,
                    tool_calls=msg.tool_calls if hasattr(msg, "tool_calls") and msg.tool_calls else None
                )
            elif isinstance(msg, ToolMessage):
                await cls.save_message(
                    conversation_id=conversation_id,
                    role="tool",
                    content=msg.content,
                    tool_call_id=msg.tool_call_id,
                    name=msg.name
                )

        # Set title on first message
        conversation = await database.conversations.find_one(
            {
                "_id": ObjectId(conversation_id)
            }
        )

        if conversation and not conversation.get("title"):

            await database.conversations.update_one(
                {
                    "_id": ObjectId(conversation_id)
                },
                {
                    "$set": {
                        "title": user_message[:50]
                    }
                }
            )

        # Get final textual response
        ai_response = ""
        for msg in reversed(new_messages):
            if isinstance(msg, AIMessage) and not (hasattr(msg, "tool_calls") and msg.tool_calls):
                ai_response = msg.content
                break
        if not ai_response and new_messages:
            ai_response = new_messages[-1].content

        return {
            "response": ai_response
        }

    @classmethod
    async def stream_chat(
        cls,
        conversation_id: str,
        user_message: str,
    ):
        # 1. Save user message immediately
        await cls.save_message(
            conversation_id=conversation_id,
            role="user",
            content=user_message,
        )

        # 2. Update conversation timestamp immediately
        await database.conversations.update_one(
            {
                "_id": ObjectId(conversation_id)
            },
            {
                "$set": {
                    "updated_at": datetime.utcnow()
                }
            }
        )

        # 3. Load previous conversation history (which now includes the user message)
        db_messages = await cls.get_messages(
            conversation_id
        )

        # 4. Convert MongoDB messages -> LangChain messages
        messages = cls.convert_messages(
            db_messages
        )

        final_response = ""
        final_messages = []

        # 5. Stream events from the agent
        async for event in agent.astream_events(
            {
                "messages": messages
            },
            version="v2"
        ):
            if event["event"] == "on_chat_model_stream":
                chunk = event["data"]["chunk"]
                if chunk.content:
                    final_response += chunk.content
                    yield chunk.content

            elif event["event"] == "on_chain_end" and event["name"] == "LangGraph":
                final_messages = event["data"]["output"]["messages"]

        # 6. Save each new message generated by the agent
        if final_messages:
            new_messages = final_messages[len(messages):]
            for msg in new_messages:
                if isinstance(msg, AIMessage):
                    await cls.save_message(
                        conversation_id=conversation_id,
                        role="assistant",
                        content=msg.content,
                        tool_calls=msg.tool_calls if hasattr(msg, "tool_calls") and msg.tool_calls else None
                    )
                elif isinstance(msg, ToolMessage):
                    await cls.save_message(
                        conversation_id=conversation_id,
                        role="tool",
                        content=msg.content,
                        tool_call_id=msg.tool_call_id,
                        name=msg.name
                    )

        # Set title on first message
        conversation = await database.conversations.find_one(
            {
                "_id": ObjectId(conversation_id)
            }
        )

        if conversation and not conversation.get("title"):

            await database.conversations.update_one(
                {
                    "_id": ObjectId(conversation_id)
                },
                {
                    "$set": {
                        "title": user_message[:50]
                    }
                }
            )